#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jul 17 12:41:36 BST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto aa3a7bff01e34f13a9a3716ec9683287 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot deaf_encoder_func_impl xil_defaultlib.deaf_encoder xil_defaultlib.glbl -log elaborate.log"
xelab -wto aa3a7bff01e34f13a9a3716ec9683287 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot deaf_encoder_func_impl xil_defaultlib.deaf_encoder xil_defaultlib.glbl -log elaborate.log

